export const SAVE_BOOKS_REQUEST = 'books:SAVE_BOOKS_REQUEST';
export const SAVE_BOOKS_SUCCESS = 'books:SAVE_BOOKS_SUCCESS';
export const SAVE_BOOKS_FAILURE = 'books:SAVE_BOOKS_FAILURE';

export const LOAD_BOOKS_REQUEST = 'books:LOAD_BOOKS_REQUEST';
export const LOAD_BOOKS_SUCCESS = 'books:LOAD_BOOKS_SUCCESS';
export const LOAD_BOOKS_FAILURE = 'books:LOAD_BOOKS_FAILURE';

export const LOAD_BOOK_REQUEST = 'books:LOAD_BOOK_REQUEST';
export const LOAD_BOOK_SUCCESS = 'books:LOAD_BOOK_SUCCESS';
export const LOAD_BOOK_FAILURE = 'books:LOAD_BOOK_FAILURE';


export const DELETE_BOOK_REQUEST = 'books:DELETE_BOOK_REQUEST';
export const DELETE_BOOK_SUCCESS = 'books:DELETE_BOOK_SUCCESS';
export const DELETE_BOOK_FAILURE = 'books:DELETE_BOOK_FAILURE';

export const UPDATE_BOOK_REQUEST = 'books:UPDATE_BOOK_REQUEST';
export const UPDATE_BOOK_SUCCESS = 'books:UPDATE_BOOK_SUCCESS';
export const UPDATE_BOOK_FAILURE = 'books:UPDATE_BOOK_FAILURE';

export const SELECT_BOOK_TO_UPDATE = 'books:SELECT_BOOK_TO_UPDATE';